name: football2vec
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.5.0
  - numba>=0.53
  - numpy>=1.21
  - pandas>=1.3
  - pillow>=8.0
  - plotly>=5.0
  - scikit-learn>=1.0
  - scipy>=1.7
  - seaborn>=0.11
  - streamlit>=1.0
  - tqdm>=4.60
  - umap-learn>=0.5
  - pip:
      - gensim>=4.0.0
      - regex
      - chart_studio
